name: CI CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
      
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/dotnetweb 
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: heatherWeb
        path: ${{env.DOTNET_ROOT}}/dotnetweb 


  staging:
    needs: build
    uses: hebrevar/githubactionsdemo/.github/workflows/publish-to-azure.yml@main
    with:
      envName: "Staging"
      envUrl: "https://heather-dotnetweb-staging.azurewebsites.net/"
      slotName: "staging"
      artifactName: "heatherWeb"
    secrets:
      azureWebAppPublishProfile: ${{ secrets.azureWebAppPublishProfile }}

  prod:
    needs: staging
    uses: hebrevar/githubactionsdemo/.github/workflows/publish-to-azure.yml@main
    with:
      envName: "Prod"
      envUrl: "https://heather-dotnetweb.azurewebsites.net/"
      slotName: "production"
      artifactName: "heatherWeb"
    secrets:
      azureWebAppPublishProfile: ${{ secrets.azureWebAppPublishProfile }}
